/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package edu.neu.csye6200.librarymanagement.views;

import edu.neu.csye6200.librarymanagement.models.Book;
import edu.neu.csye6200.librarymanagement.utils.OperatingSystem;
import java.awt.Color;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Pavan munaganti
 */
public class BooksCrudPanel extends javax.swing.JPanel {

    private List<Book> booksList;
    /**
     * Creates new form BooksCrudPanel
     */
    public BooksCrudPanel() {
        initComponents();
        populateBooksList();
        populateBooksTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        booksTable = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        bookId = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        bookName = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        bookEdition = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        bookAuthor = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        bookPublisher = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        bookQuantity = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        booksRemaining = new javax.swing.JTextField();
        studentDeleteBtn = new javax.swing.JButton();
        studentUpdateBtn = new javax.swing.JButton();
        studentCreateBtn = new javax.swing.JButton();

        setName("booksPanel"); // NOI18N

        jLabel10.setBackground(new java.awt.Color(255, 43, 48));
        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 43, 48));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Book Management");

        booksTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Book Id", "Book Name", "Author", "Publisher", "Edition", "Quantity", "Remaining"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        booksTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                booksTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(booksTable);
        if (booksTable.getColumnModel().getColumnCount() > 0) {
            booksTable.getColumnModel().getColumn(0).setResizable(false);
            booksTable.getColumnModel().getColumn(1).setResizable(false);
            booksTable.getColumnModel().getColumn(2).setResizable(false);
            booksTable.getColumnModel().getColumn(3).setResizable(false);
            booksTable.getColumnModel().getColumn(4).setResizable(false);
            booksTable.getColumnModel().getColumn(5).setResizable(false);
            booksTable.getColumnModel().getColumn(6).setResizable(false);
        }

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 0, 0));
        jLabel9.setText("Book Id");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Book Name");

        bookName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookNameActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Edition");

        bookEdition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookEditionActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Author");

        bookAuthor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookAuthorActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Publisher");

        bookPublisher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookPublisherActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Quantity");

        bookQuantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookQuantityActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Remaining");

        booksRemaining.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                booksRemainingActionPerformed(evt);
            }
        });

        studentDeleteBtn.setBackground(new java.awt.Color(255, 43, 45));
        studentDeleteBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        studentDeleteBtn.setForeground(new java.awt.Color(255, 255, 255));
        studentDeleteBtn.setText("Delete");
        studentDeleteBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                studentDeleteBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                studentDeleteBtnMouseExited(evt);
            }
        });

        studentUpdateBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        studentUpdateBtn.setText("Update");
        studentUpdateBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                studentUpdateBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                studentUpdateBtnMouseExited(evt);
            }
        });

        studentCreateBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        studentCreateBtn.setText("Create");
        studentCreateBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                studentCreateBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                studentCreateBtnMouseExited(evt);
            }
        });
        studentCreateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentCreateBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(383, 383, 383)
                                .addComponent(jLabel10))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(153, 153, 153)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(369, 369, 369)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(bookEdition, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(bookName, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(bookId, javax.swing.GroupLayout.PREFERRED_SIZE, 587, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(studentCreateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(studentUpdateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(12, 12, 12)
                                            .addComponent(studentDeleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(bookAuthor, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(65, 65, 65)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(bookPublisher, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(bookQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(65, 65, 65)
                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(booksRemaining, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 155, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bookId, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bookName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(bookEdition, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bookPublisher, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(bookAuthor, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2)
                        .addComponent(jLabel6)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(bookQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(booksRemaining, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(studentDeleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(studentUpdateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(studentCreateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bookNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bookNameActionPerformed

    private void bookEditionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookEditionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bookEditionActionPerformed

    private void bookAuthorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookAuthorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bookAuthorActionPerformed

    private void bookPublisherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookPublisherActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bookPublisherActionPerformed

    private void bookQuantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookQuantityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bookQuantityActionPerformed

    private void booksRemainingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_booksRemainingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_booksRemainingActionPerformed

    private void studentDeleteBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_studentDeleteBtnMouseEntered
        // TODO add your handling code here:
        studentDeleteBtn.setBackground(new Color(0, 0, 0));
    }//GEN-LAST:event_studentDeleteBtnMouseEntered

    private void studentDeleteBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_studentDeleteBtnMouseExited
        // TODO add your handling code here:
        studentDeleteBtn.setBackground(new Color(255, 43, 48));
    }//GEN-LAST:event_studentDeleteBtnMouseExited

    private void studentUpdateBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_studentUpdateBtnMouseEntered
        // TODO add your handling code here:
        studentUpdateBtn.setBackground(new Color(0,0,0));
        studentUpdateBtn.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_studentUpdateBtnMouseEntered

    private void studentUpdateBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_studentUpdateBtnMouseExited
        // TODO add your handling code here:
        studentUpdateBtn.setBackground(new Color(255,255,255));
        studentUpdateBtn.setForeground(new Color(0, 0, 0));
    }//GEN-LAST:event_studentUpdateBtnMouseExited

    private void studentCreateBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_studentCreateBtnMouseEntered
        // TODO add your handling code here:
        studentCreateBtn.setBackground(new Color(0,0,0));
        studentCreateBtn.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_studentCreateBtnMouseEntered

    private void studentCreateBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_studentCreateBtnMouseExited
        // TODO add your handling code here:
        studentCreateBtn.setBackground(new Color(255,255,255));
        studentCreateBtn.setForeground(new Color(0, 0, 0));
    }//GEN-LAST:event_studentCreateBtnMouseExited

    private void studentCreateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentCreateBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_studentCreateBtnActionPerformed

    private void booksTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_booksTableMouseClicked
        // TODO add your handling code here:
        if(booksTable.getSelectedRow() != -1){
            Book book = booksList.get(booksTable.getSelectedRow());
            bookId.setText(book.getId());
            bookName.setText(book.getBookName());
            bookAuthor.setText(book.getBookAuthor());
            bookPublisher.setText(book.getBookPublisher());
            bookEdition.setText(String.valueOf(book.getBookEdition()));
            bookQuantity.setText(String.valueOf(book.getBookQuantity()));
            booksRemaining.setText(String.valueOf(book.getRemainingBooks()));
        }
        else{
            bookId.setText("");
            bookName.setText("");
            bookAuthor.setText("");
            bookPublisher.setText("");
            bookEdition.setText("");
            bookQuantity.setText("");
            booksRemaining.setText("");
        }
    }//GEN-LAST:event_booksTableMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bookAuthor;
    private javax.swing.JTextField bookEdition;
    private javax.swing.JTextField bookId;
    private javax.swing.JTextField bookName;
    private javax.swing.JTextField bookPublisher;
    private javax.swing.JTextField bookQuantity;
    private javax.swing.JTextField booksRemaining;
    private javax.swing.JTable booksTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton studentCreateBtn;
    private javax.swing.JButton studentDeleteBtn;
    private javax.swing.JButton studentUpdateBtn;
    // End of variables declaration//GEN-END:variables

    private void populateBooksTable(){
        
        DefaultTableModel model = (DefaultTableModel) booksTable.getModel();
        model.setRowCount(0);
        
        for(Book book : booksList){
            Object[] row = new Object[7];
            
            String[] bookString = book.toString().split(",");
            
            for (int i = 0; i < 7; i++) {
                row[i] = bookString[i];
            }
            
            model.addRow(row);
        }
    }

    private void populateBooksList() {
        booksList = OperatingSystem.getInstance().getBooks();
    }
}
