/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package edu.neu.csye6200.librarymanagement.views;

import edu.neu.csye6200.librarymanagement.models.Book;
import edu.neu.csye6200.librarymanagement.utils.OperatingSystem;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Raja Shekar
 */
public class SearchBooks extends javax.swing.JPanel {

    private List<Book> booksList;
    /**
     * Creates new form SearchBooks
     */
    public SearchBooks() {
        initComponents();
        filterButtonGroup.add(nameFilter);
        filterButtonGroup.add(idFilter);
        filterButtonGroup.add(authorFilter);
        nameFilter.setSelected(true);
        
        populateBooks();
        populateBooksTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        filterButtonGroup = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        booksTable = new javax.swing.JTable();
        jLabel18 = new javax.swing.JLabel();
        searchFieldTxt = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        idFilter = new javax.swing.JRadioButton();
        nameFilter = new javax.swing.JRadioButton();
        authorFilter = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        findBooksBtn = new javax.swing.JButton();

        booksTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Book ID", "Book Name", "Author", "Publisher", "Edition", "Total Books", "Available Books"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(booksTable);

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel18.setText("Search:");

        searchFieldTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchFieldTxtActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel19.setText("Filter:");

        idFilter.setText("ID");

        nameFilter.setText("Name");

        authorFilter.setText("Author");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 0));
        jLabel1.setText("Search Books");

        findBooksBtn.setBackground(new java.awt.Color(204, 0, 0));
        findBooksBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        findBooksBtn.setForeground(new java.awt.Color(255, 255, 255));
        findBooksBtn.setText("Find");
        findBooksBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findBooksBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jLabel18)
                        .addGap(18, 18, 18)
                        .addComponent(searchFieldTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(findBooksBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addComponent(jLabel19)
                        .addGap(28, 28, 28)
                        .addComponent(idFilter)
                        .addGap(18, 18, 18)
                        .addComponent(nameFilter)
                        .addGap(18, 18, 18)
                        .addComponent(authorFilter)
                        .addGap(0, 268, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(391, 391, 391)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchFieldTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idFilter)
                    .addComponent(nameFilter)
                    .addComponent(authorFilter)
                    .addComponent(findBooksBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 590, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void searchFieldTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchFieldTxtActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_searchFieldTxtActionPerformed

    private void findBooksBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findBooksBtnActionPerformed
        // TODO add your handling code here:
        
        populateBooks();
        populateBooksTable();
    }//GEN-LAST:event_findBooksBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton authorFilter;
    private javax.swing.JTable booksTable;
    private javax.swing.ButtonGroup filterButtonGroup;
    private javax.swing.JButton findBooksBtn;
    private javax.swing.JRadioButton idFilter;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton nameFilter;
    private javax.swing.JTextField searchFieldTxt;
    // End of variables declaration//GEN-END:variables

    private void populateBooks() {
        
        String searchFilter = searchFieldTxt.getText().trim().toLowerCase();
        if(searchFilter.length() == 0){
            booksList = OperatingSystem.getInstance().getBooks();
        }
        else{
            if(idFilter.isSelected()){
                booksList = OperatingSystem.getInstance().getBooks().stream().filter(book -> book.getId().toLowerCase().contains(searchFilter)).toList();
            }
            else if(nameFilter.isSelected()){
                booksList = OperatingSystem.getInstance().getBooks().stream().filter(book -> book.getBookName().toLowerCase().contains(searchFilter)).toList();
            }
            else{
                booksList = OperatingSystem.getInstance().getBooks().stream().filter(book -> book.getBookAuthor().toLowerCase().contains(searchFilter)).toList();
            }
        }
    }

    private void populateBooksTable() {
        DefaultTableModel model = (DefaultTableModel) booksTable.getModel();
        model.setRowCount(0);
        
        for(Book book : booksList){
            Object[] row = new Object[7];
            
            String[] bookString = book.toString().split(",");
            
            for (int i = 0; i < 7; i++) {
                row[i] = bookString[i];
            }
            
            model.addRow(row);
        }
    }
}
