/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package edu.neu.csye6200.librarymanagement.views;

import edu.neu.csye6200.librarymanagement.models.User;
import java.awt.Color;
import javax.swing.JFrame;

/**
 *
 * @author Pavan munaganti
 */
public class StaffDashboard extends javax.swing.JFrame {
    public static JFrame staffDashboard;
    User staff;
    /**
     * Creates new form StaffDashboard
     */
    public StaffDashboard(User staff) {
        initComponents();
        this.staff = staff;
        ReturnBook returnBookPanel= new ReturnBook();
        staffSplitPane.setRightComponent(returnBookPanel);
        returnBook.setBackground(new Color(0,0,0));
        issueBooks.setBackground(new Color(204, 0, 0));
        manageBooksBtn.setBackground(new Color(204, 0, 0));
        manageStudentsBtn.setBackground(new Color(204, 0, 0));
        logoutBtn.setBackground(new Color(204, 0, 0));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        staffSplitPane = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        issueBooks = new javax.swing.JButton();
        manageBooksBtn = new javax.swing.JButton();
        manageStudentsBtn = new javax.swing.JButton();
        logoutBtn = new javax.swing.JButton();
        returnBook = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        staffSplitPane.setDividerLocation(200);
        staffSplitPane.setDividerSize(0);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 990, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 755, Short.MAX_VALUE)
        );

        staffSplitPane.setRightComponent(jPanel1);

        jPanel2.setBackground(new java.awt.Color(204, 0, 0));

        jPanel3.setBackground(new java.awt.Color(204, 0, 0));

        issueBooks.setBackground(new java.awt.Color(204, 0, 0));
        issueBooks.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        issueBooks.setForeground(new java.awt.Color(255, 255, 255));
        issueBooks.setText("Issue Book");
        issueBooks.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        issueBooks.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                issueBooksMouseEntered(evt);
            }
        });
        issueBooks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                issueBooksActionPerformed(evt);
            }
        });

        manageBooksBtn.setBackground(new java.awt.Color(204, 0, 0));
        manageBooksBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        manageBooksBtn.setForeground(new java.awt.Color(255, 255, 255));
        manageBooksBtn.setText("Manage Books");
        manageBooksBtn.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        manageBooksBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageBooksBtnActionPerformed(evt);
            }
        });

        manageStudentsBtn.setBackground(new java.awt.Color(204, 0, 0));
        manageStudentsBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        manageStudentsBtn.setForeground(new java.awt.Color(255, 255, 255));
        manageStudentsBtn.setText("Students");
        manageStudentsBtn.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        manageStudentsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageStudentsBtnActionPerformed(evt);
            }
        });

        logoutBtn.setBackground(new java.awt.Color(204, 0, 0));
        logoutBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        logoutBtn.setForeground(new java.awt.Color(255, 255, 255));
        logoutBtn.setText("Logout");
        logoutBtn.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        logoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutBtnActionPerformed(evt);
            }
        });

        returnBook.setBackground(new java.awt.Color(204, 0, 0));
        returnBook.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        returnBook.setForeground(new java.awt.Color(255, 255, 255));
        returnBook.setText("Return");
        returnBook.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        returnBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnBookActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(issueBooks, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(manageBooksBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(manageStudentsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(logoutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(9, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(returnBook, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(returnBook)
                .addGap(17, 17, 17)
                .addComponent(issueBooks)
                .addGap(18, 18, 18)
                .addComponent(manageBooksBtn)
                .addGap(18, 18, 18)
                .addComponent(manageStudentsBtn)
                .addGap(18, 18, 18)
                .addComponent(logoutBtn)
                .addContainerGap(90, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(214, 214, 214)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(250, Short.MAX_VALUE))
        );

        staffSplitPane.setLeftComponent(jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(staffSplitPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(staffSplitPane, javax.swing.GroupLayout.DEFAULT_SIZE, 755, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void manageBooksBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageBooksBtnActionPerformed
        // TODO add your handling code here:
        BooksCrudPanel booksCrud= new BooksCrudPanel();
        staffSplitPane.setRightComponent(booksCrud);
        returnBook.setBackground(new Color(204, 0, 0));
        issueBooks.setBackground(new Color(204, 0, 0));
        manageBooksBtn.setBackground(new Color(0,0,0));
        manageStudentsBtn.setBackground(new Color(204, 0, 0));
        logoutBtn.setBackground(new Color(204, 0, 0));
    }//GEN-LAST:event_manageBooksBtnActionPerformed

    private void manageStudentsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageStudentsBtnActionPerformed
        // TODO add your handling code here:
        StudentsCrudPanel studentsCrud= new StudentsCrudPanel();
        staffSplitPane.setRightComponent(studentsCrud);
        returnBook.setBackground(new Color(204, 0, 0));
        issueBooks.setBackground(new Color(204, 0, 0));
        manageBooksBtn.setBackground(new Color(204, 0, 0));
        manageStudentsBtn.setBackground(new Color(0,0,0));
        logoutBtn.setBackground(new Color(204, 0, 0));
    }//GEN-LAST:event_manageStudentsBtnActionPerformed

    private void logoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBtnActionPerformed
        // TODO add your handling code here:
        staffDashboard.setVisible(false);
        LoginFrame.loginFrame.setVisible(true);
    }//GEN-LAST:event_logoutBtnActionPerformed

    private void issueBooksMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_issueBooksMouseEntered
        // TODO add your handling code here:
        
    }//GEN-LAST:event_issueBooksMouseEntered

    private void issueBooksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_issueBooksActionPerformed
        // TODO add your handling code here:
        IssueBookPanel issueBook= new IssueBookPanel();
        staffSplitPane.setRightComponent(issueBook);
        returnBook.setBackground(new Color(204, 0, 0));
        issueBooks.setBackground(new Color(0,0,0));
        manageBooksBtn.setBackground(new Color(204, 0, 0));
        manageStudentsBtn.setBackground(new Color(204,0,0));
        logoutBtn.setBackground(new Color(204, 0, 0)); 
        
    }//GEN-LAST:event_issueBooksActionPerformed

    private void returnBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnBookActionPerformed
        // TODO add your handling code here:
        ReturnBook returnBookPanel= new ReturnBook();
        staffSplitPane.setRightComponent(returnBookPanel);
        returnBook.setBackground(new Color(0,0,0));
        issueBooks.setBackground(new Color(204, 0, 0));
        manageBooksBtn.setBackground(new Color(204, 0, 0));
        manageStudentsBtn.setBackground(new Color(204, 0, 0));
        logoutBtn.setBackground(new Color(204, 0, 0));
    }//GEN-LAST:event_returnBookActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton issueBooks;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton logoutBtn;
    private javax.swing.JButton manageBooksBtn;
    private javax.swing.JButton manageStudentsBtn;
    private javax.swing.JButton returnBook;
    private javax.swing.JSplitPane staffSplitPane;
    // End of variables declaration//GEN-END:variables
}
