/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package edu.neu.csye6200.librarymanagement.views;

import edu.neu.csye6200.librarymanagement.models.User;
import java.awt.Color;
import javax.swing.JFrame;

/**
 *
 * @author Pavan munaganti
 */
public class StudentDashboard extends javax.swing.JFrame {
    public static JFrame studentDashboard;
    User student;
    /**
     * Creates new form StudentDashboard
     */
    public StudentDashboard(User student) {
        initComponents();
        this.student = student;
        StudentBooksBorrowed returnBookPanel= new StudentBooksBorrowed();
        studentSplitPane.setRightComponent(returnBookPanel);
        studentBooksBorrowed.setBackground(new Color(0,0,0));
        studentLogout.setBackground(new Color(204, 0, 0));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        studentSplitPane = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        studentProfile = new javax.swing.JButton();
        studentBooksBorrowed = new javax.swing.JButton();
        studentLogout = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        studentSplitPane.setDividerLocation(200);
        studentSplitPane.setDividerSize(0);

        jPanel1.setBackground(new java.awt.Color(204, 0, 0));

        jPanel3.setBackground(new java.awt.Color(204, 0, 0));

        studentProfile.setBackground(new java.awt.Color(204, 0, 0));
        studentProfile.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        studentProfile.setForeground(new java.awt.Color(255, 255, 255));
        studentProfile.setText("Profile");
        studentProfile.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));

        studentBooksBorrowed.setBackground(new java.awt.Color(204, 0, 0));
        studentBooksBorrowed.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        studentBooksBorrowed.setForeground(new java.awt.Color(255, 255, 255));
        studentBooksBorrowed.setText("Books Borrowed");
        studentBooksBorrowed.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));

        studentLogout.setBackground(new java.awt.Color(204, 0, 0));
        studentLogout.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        studentLogout.setForeground(new java.awt.Color(255, 255, 255));
        studentLogout.setText("Logout");
        studentLogout.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(studentProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(studentBooksBorrowed, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(studentLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(studentProfile)
                .addGap(19, 19, 19)
                .addComponent(studentBooksBorrowed)
                .addGap(19, 19, 19)
                .addComponent(studentLogout)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(283, 283, 283)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(319, Short.MAX_VALUE))
        );

        studentSplitPane.setLeftComponent(jPanel1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 990, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 755, Short.MAX_VALUE)
        );

        studentSplitPane.setRightComponent(jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(studentSplitPane, javax.swing.GroupLayout.DEFAULT_SIZE, 1190, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(studentSplitPane)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adminStaffBtn;
    private javax.swing.JButton adminStaffBtn1;
    private javax.swing.JButton adminStaffBtn2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton studentBooksBorrowed;
    private javax.swing.JButton studentLogout;
    private javax.swing.JButton studentProfile;
    private javax.swing.JSplitPane studentSplitPane;
    // End of variables declaration//GEN-END:variables
}
