/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package edu.neu.csye6200.librarymanagement.views;

import edu.neu.csye6200.librarymanagement.models.Student;
import edu.neu.csye6200.librarymanagement.models.User;
import edu.neu.csye6200.librarymanagement.models.User.UserRole;
import edu.neu.csye6200.librarymanagement.utils.OperatingSystem;
import edu.neu.csye6200.librarymanagement.validators.EmailVerifier;
import edu.neu.csye6200.librarymanagement.validators.IdVerifier;
import edu.neu.csye6200.librarymanagement.validators.NumberVerifier;
import edu.neu.csye6200.librarymanagement.validators.UsernameVerifier;
import edu.neu.csye6200.librarymanagement.validators.WordVerifier;
import java.awt.Color;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Pavan munaganti
 */
public class StudentsCrudPanel extends javax.swing.JPanel {

    private List<User> studentsList;
    /**
     * Creates new form AdminBooksPanel
     */
    public StudentsCrudPanel() {
        initComponents();
        populateStudentsList();
        populateStudentsTable();
        adminStudentUpdateBtn.setEnabled(false);
        adminStudentDeleteBtn.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        adminStudentTable = new javax.swing.JTable();
        adminStudentFname = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        adminStudentMail = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        adminStudentUsername = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        adminStudentLname = new javax.swing.JTextField();
        adminStudentPhoneNo = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        adminStudentId = new javax.swing.JTextField();
        adminStudentUpdateBtn = new javax.swing.JButton();
        adminStudentDeleteBtn = new javax.swing.JButton();
        adminStudentCreateBtn = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        adminStudentPassword = new javax.swing.JPasswordField();

        setName("adminStudentsPanel"); // NOI18N

        adminStudentTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Husky Id", "First Name", "Last Name", "Email Id", "Phone Number", "Username"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        adminStudentTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                adminStudentTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(adminStudentTable);

        adminStudentFname.setInputVerifier(new WordVerifier());
        adminStudentFname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminStudentFnameActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("First Name");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Mail Id");

        adminStudentMail.setInputVerifier(new EmailVerifier());
        adminStudentMail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminStudentMailActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Username");

        adminStudentUsername.setInputVerifier(new UsernameVerifier());
        adminStudentUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminStudentUsernameActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Last Name");

        adminStudentLname.setInputVerifier(new WordVerifier());
        adminStudentLname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminStudentLnameActionPerformed(evt);
            }
        });

        adminStudentPhoneNo.setInputVerifier(new NumberVerifier());
        adminStudentPhoneNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminStudentPhoneNoActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Phone No");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Password");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 0, 0));
        jLabel9.setText("Husky Id");

        adminStudentId.setInputVerifier(new IdVerifier());

        adminStudentUpdateBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        adminStudentUpdateBtn.setText("Update");
        adminStudentUpdateBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                adminStudentUpdateBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                adminStudentUpdateBtnMouseExited(evt);
            }
        });
        adminStudentUpdateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminStudentUpdateBtnActionPerformed(evt);
            }
        });

        adminStudentDeleteBtn.setBackground(new java.awt.Color(255, 43, 45));
        adminStudentDeleteBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        adminStudentDeleteBtn.setForeground(new java.awt.Color(255, 255, 255));
        adminStudentDeleteBtn.setText("Delete");
        adminStudentDeleteBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                adminStudentDeleteBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                adminStudentDeleteBtnMouseExited(evt);
            }
        });
        adminStudentDeleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminStudentDeleteBtnActionPerformed(evt);
            }
        });

        adminStudentCreateBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        adminStudentCreateBtn.setText("Create");
        adminStudentCreateBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                adminStudentCreateBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                adminStudentCreateBtnMouseExited(evt);
            }
        });
        adminStudentCreateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminStudentCreateBtnActionPerformed(evt);
            }
        });

        jLabel10.setBackground(new java.awt.Color(255, 43, 48));
        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 43, 48));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Student Management");

        adminStudentPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminStudentPasswordActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 975, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(154, 154, 154)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(adminStudentMail, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(65, 65, 65)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(adminStudentLname, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(adminStudentPhoneNo, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(adminStudentFname, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(adminStudentId, javax.swing.GroupLayout.PREFERRED_SIZE, 587, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(adminStudentUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(65, 65, 65)
                                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(adminStudentPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(adminStudentCreateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(adminStudentUpdateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(12, 12, 12)
                                            .addComponent(adminStudentDeleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(383, 383, 383)
                                .addComponent(jLabel10)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel10)
                .addGap(37, 37, 37)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(adminStudentId, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(adminStudentFname, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(adminStudentLname, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(adminStudentMail, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(adminStudentPhoneNo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(adminStudentUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4))
                    .addComponent(jLabel8)
                    .addComponent(adminStudentPassword))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(adminStudentDeleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(adminStudentUpdateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(adminStudentCreateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(71, 71, 71))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void adminStudentFnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminStudentFnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adminStudentFnameActionPerformed

    private void adminStudentMailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminStudentMailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adminStudentMailActionPerformed

    private void adminStudentUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminStudentUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adminStudentUsernameActionPerformed

    private void adminStudentLnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminStudentLnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adminStudentLnameActionPerformed

    private void adminStudentPhoneNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminStudentPhoneNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adminStudentPhoneNoActionPerformed

    private void adminStudentUpdateBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminStudentUpdateBtnMouseEntered
        // TODO add your handling code here:
        adminStudentUpdateBtn.setBackground(new Color(0,0,0));
        adminStudentUpdateBtn.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_adminStudentUpdateBtnMouseEntered

    private void adminStudentUpdateBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminStudentUpdateBtnMouseExited
        // TODO add your handling code here:
        adminStudentUpdateBtn.setBackground(new Color(255,255,255));
        adminStudentUpdateBtn.setForeground(new Color(0, 0, 0));
    }//GEN-LAST:event_adminStudentUpdateBtnMouseExited

    private void adminStudentDeleteBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminStudentDeleteBtnMouseEntered
        // TODO add your handling code here:
        adminStudentDeleteBtn.setBackground(new Color(0, 0, 0));
    }//GEN-LAST:event_adminStudentDeleteBtnMouseEntered

    private void adminStudentDeleteBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminStudentDeleteBtnMouseExited
        // TODO add your handling code here:
        adminStudentDeleteBtn.setBackground(new Color(255, 43, 48));
    }//GEN-LAST:event_adminStudentDeleteBtnMouseExited

    private void adminStudentCreateBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminStudentCreateBtnMouseEntered
        // TODO add your handling code here:
        adminStudentCreateBtn.setBackground(new Color(0,0,0));
        adminStudentCreateBtn.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_adminStudentCreateBtnMouseEntered

    private void adminStudentCreateBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminStudentCreateBtnMouseExited
        // TODO add your handling code here:
        adminStudentCreateBtn.setBackground(new Color(255,255,255));
        adminStudentCreateBtn.setForeground(new Color(0, 0, 0));
    }//GEN-LAST:event_adminStudentCreateBtnMouseExited

    private void adminStudentCreateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminStudentCreateBtnActionPerformed
        // TODO add your handling code here:
        
        String id = adminStudentId.getText();
        String fname = adminStudentFname.getText();
        String lname = adminStudentLname.getText();
        String mail = adminStudentMail.getText();
        String phoneno = adminStudentPhoneNo.getText();
        String username = adminStudentUsername.getText();
        String password = new String(adminStudentPassword.getPassword());
        
        if(studentsList.stream().map(user -> user.getId()).toList().contains(id)){
            JOptionPane.showMessageDialog(this, "Student with this ID already exists. Please check again");
            return;
        }
        
        User user = new User(id, fname, lname, mail, phoneno, username, password, UserRole.STUDENT);
        
        OperatingSystem.getInstance().getUsers().add(user);
        OperatingSystem.getInstance().writeUsers();
        
        
        adminStudentId.setText("");
        adminStudentFname.setText("");
        adminStudentLname.setText("");
        adminStudentMail.setText("");
        adminStudentPhoneNo.setText("");
        adminStudentUsername.setText("");
        adminStudentPassword.setText("");


        populateStudentsList();
        populateStudentsTable();
        
    }//GEN-LAST:event_adminStudentCreateBtnActionPerformed

    private void adminStudentTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminStudentTableMouseClicked
        // TODO add your handling code here:
        if(adminStudentTable.getSelectedRow() != -1){
            User user = studentsList.get(adminStudentTable.getSelectedRow());
            adminStudentId.setText(user.getId());
            adminStudentFname.setText(user.getFirstName());
            adminStudentLname.setText(user.getLastName());
            adminStudentMail.setText(user.getEmail());
            adminStudentPhoneNo.setText(user.getPhoneNumber());
            adminStudentUsername.setText(user.getUsername());
            adminStudentPassword.setText(user.getPassword());
            
            adminStudentId.setEnabled(false);
            adminStudentCreateBtn.setEnabled(false);
            adminStudentUpdateBtn.setEnabled(true);
            adminStudentDeleteBtn.setEnabled(true);
        }
        else{
            adminStudentId.setText("");
            adminStudentFname.setText("");
            adminStudentLname.setText("");
            adminStudentMail.setText("");
            adminStudentPhoneNo.setText("");
            adminStudentUsername.setText("");
            adminStudentPassword.setText("");
            
            adminStudentId.setEnabled(true);
            adminStudentCreateBtn.setEnabled(true);
            adminStudentUpdateBtn.setEnabled(false);
            adminStudentDeleteBtn.setEnabled(false);
        }
    }//GEN-LAST:event_adminStudentTableMouseClicked

    private void adminStudentUpdateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminStudentUpdateBtnActionPerformed
        // TODO add your handling code here:
        String id = adminStudentId.getText();
        String fname = adminStudentFname.getText();
        String lname = adminStudentLname.getText();
        String mail = adminStudentMail.getText();
        String phoneno = adminStudentPhoneNo.getText();
        String username = adminStudentUsername.getText();
        String password = new String(adminStudentPassword.getPassword());
        
        User user = studentsList.stream().filter(u -> u.getId().equals(id)).findFirst().orElse(null);
        
        user.setFirstName(fname);
        user.setLastName(lname);
        user.setEmail(mail);
        user.setPhoneNumber(phoneno);
        user.setUsername(username);
        user.setPassword(password);
        
        OperatingSystem.getInstance().writeUsers();
        
        adminStudentId.setText("");
        adminStudentFname.setText("");
        adminStudentLname.setText("");
        adminStudentMail.setText("");
        adminStudentPhoneNo.setText("");
        adminStudentUsername.setText("");
        adminStudentPassword.setText("");
        
        populateStudentsList();
        populateStudentsTable();

        adminStudentId.setEnabled(true);
        adminStudentCreateBtn.setEnabled(true);
        adminStudentUpdateBtn.setEnabled(false);
        adminStudentDeleteBtn.setEnabled(false);
    }//GEN-LAST:event_adminStudentUpdateBtnActionPerformed

    private void adminStudentDeleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminStudentDeleteBtnActionPerformed
        // TODO add your handling code here:
        
        if(JOptionPane.showConfirmDialog(this, "Do you really want to delete this student record") == JOptionPane.YES_OPTION){
            
            String id = adminStudentId.getText();
        
            User user = studentsList.stream().filter(u -> u.getId().equals(id)).findFirst().orElse(null);
            
            OperatingSystem.getInstance().getUsers().remove(user);
            OperatingSystem.getInstance().writeUsers();
            
            adminStudentId.setText("");
            adminStudentFname.setText("");
            adminStudentLname.setText("");
            adminStudentMail.setText("");
            adminStudentPhoneNo.setText("");
            adminStudentUsername.setText("");
            adminStudentPassword.setText("");

            populateStudentsList();
            populateStudentsTable();

            adminStudentId.setEnabled(true);
            adminStudentCreateBtn.setEnabled(true);
            adminStudentUpdateBtn.setEnabled(false);
            adminStudentDeleteBtn.setEnabled(false);
        
        }
    }//GEN-LAST:event_adminStudentDeleteBtnActionPerformed

    private void adminStudentPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminStudentPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adminStudentPasswordActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adminStudentCreateBtn;
    private javax.swing.JButton adminStudentDeleteBtn;
    private javax.swing.JTextField adminStudentFname;
    private javax.swing.JTextField adminStudentId;
    private javax.swing.JTextField adminStudentLname;
    private javax.swing.JTextField adminStudentMail;
    private javax.swing.JPasswordField adminStudentPassword;
    private javax.swing.JTextField adminStudentPhoneNo;
    private javax.swing.JTable adminStudentTable;
    private javax.swing.JButton adminStudentUpdateBtn;
    private javax.swing.JTextField adminStudentUsername;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    private void populateStudentsList() {
        
        studentsList = OperatingSystem.getInstance().getUsers().stream().filter(user -> user.getRole().equals(UserRole.STUDENT)).toList();
    }

    private void populateStudentsTable() {
        DefaultTableModel model = (DefaultTableModel) adminStudentTable.getModel();
        model.setRowCount(0);
        
        for(User user : studentsList){
            Object[] row = new Object[6];
            
            String[] userString = user.toString().split(",");
            
            for (int i = 0; i < 6; i++) {
                row[i] = userString[i];
            }
            
            model.addRow(row);
        }
    }
}
